# dados_iniciais.py

CSV_FABRICA = """Nome da Planta;Tipo;Nome Popular 1;Nome Popular 2;Nome Popular 3;Tempo de Colheita (Em Dias);Frequência de Rega (Em Dias);Quantidade de Sol;Planta que Cresce Bem Junto 1;Planta que Cresce Bem Junto 2;Planta que Cresce Bem Junto 3;Planta que Cresce Mal Junto 1;Planta que Cresce Mal Junto 2;Planta que Cresce Mal Junto 3;Fonte 1;Fonte 2;Fonte 3
Abacateiro;Alimentícia;;;;;;;;;;Alface;;;OLIVEIRA et al., 2018;;
Abacaxi;Alimentícia;;;;390;;;;;;;;;POLETTO et al., 2020;;
Abóbora;Alimentícia;;;;;;;;;;;;;;;
Monjoleiro;Agroflorestais;Espinheiro-preto;Angico-branco;Gorocaia;Sazonal: Mar-Out;7;Sol Pleno;N/A;N/A;N/A;N/A;N/A;N/A;CARVALHO, 2008;;
Açaí;Agroflorestais;Açaí-do-Pará;Açaí-da-Amazonia;;;;;;;;;;;;;
Alcaçuz;Medicinais/Chás;;;;;;;;;;;;;;;
Alecrim;Alimentícia;;;;;;;;;;;;;;;
Alface;Alimentícia;;;;;;;Abacateiro;;;;;OLIVEIRA et al., 2018;;
Alfafa;Outros;;;;;;;;;;;;;;;
Algodão;Outros;Algodão;;;;;;;;;;;;;;
Alho;Alimentícia;;;;;;;;;;;;;;;
Alamanda;Ornamentais;;;;;;;;;;;;;;;
Amendoim-bravo;Agroflorestais;Amendoim;Ibiraró;Bálsamo;Sazonal: Mai-Nov;7;Sol Pleno;Espécies pioneiras;N/A;N/A;Povoamentos puros;N/A;N/A;CARVALHO, 2003;;
Amor-perfeito;Ornamentais;;;;;;;;;;;;;;;
Andiroba;Agroflorestais;Jandiroba;Nandiroba;Andirobeira;Sazonal: Set-Jan;7;Sol Pleno;Açaizeiro;Ucuúba;N/A;N/A;N/A;N/A;CARVALHO, 2014;;
Angélica;Medicinais/Chás;;;;;;;;;;;;;;;
Angico-branco;Agroflorestais;Angico-liso;Curupaí;Cambuí;Sazonal: Jul-Nov;10;Sol Pleno;Plantio puro;;;;;;CARVALHO, 2003;;
Angico-vermelho;Agroflorestais;Angico-da-mata;Aperta-ruão;;;;;;;;;;;;;
Araribá-rosa;Agroflorestais;Araribá;;;;;;;;;;;;;;
Araticum do Mato;Agroflorestais;Araticum;Cortiça-Amarela;Pasmada-do-Mato;;;;;;;;;;;;
Araticum-alvadio;Agroflorestais;Araticum;;;;;;;;;;;;;
Araticum-Cagão;Agroflorestais;Araticum;Coração-de-Boi;Cortição;;;;;;;;;;;;
Aroeira;Agroflorestais;;;;;;;;;;;;;;;
Aroeira-salsa;Agroflorestais;Aroeira-periquita;Anacauíta;;;;;;;;;;;;;
Arroz;Alimentícia;;;;;;;;;;;;;;;
Arruda;Religiosidades;;;;;;;;;;;;;;;
Atanásia;Medicinais/Chás;Catinga-de-mulata;Erva-lombrigueira;Palma-crespa;;;;;;;;;;;;
Aveia-preta;Outros;;;;;;;;;;;;;;;
Ayahuasca;Religiosidades;Chacrona;;;;;;;;;;;;;;
Azaleia;Ornamentais;;;;;;;;;;;;;;;
Azevem;Outros;;;;;;;;;;;;;;;
Babaçu;Outros;Baguaçu;Aguaçu;;;;;Melancia;;;;;;SILVA, 2017;;
Bacaba;Agroflorestais;;;;;;;;;;;;;;;
Bacupari;Agroflorestais;;;;;;;;;;;;;;;
Bambu-japones;Religiosidades;;;;;;;;;;;;;;;
Banana;Alimentícia;;;;300;;;Brócolis;;;;;;POLETTO et al., 2020;;
Baobá;Religiosidades;;;;;;;;;;;;;;;
Barbasco;Outros;;;;;;;;;;;;;;;
Barbatimão;Agroflorestais;;;;;;;;;;;;;;;
Baru;Agroflorestais;Coco-Pereba;Baru;Castanha-de-Burro;;;;;;;;;;;;
Batata;Alimentícia;;;;;;;;;;;;;;;
Begônia-rex;Ornamentais;;;;;;;;;;;;;;;
Beldroega;Outros;Verdolaga;;;;;;;;;;;;;;
Biribá;Agroflorestais;Araticum;Araticum Ponhé;Biribá-das-Antilhas;;;;;;;;;;;;
Boldo-do-chile;Medicinais/Chás;;;;;;;;;;;;;;;
Bonsai;Religiosidades;;;;;;;;;;;;;;;
Bougainvillea;Ornamentais;Primavera;;;;;;;;;;;;;;
Bracatinga;Agroflorestais;;;;;;;;;;;;;;;
Brócolis;Alimentícia;;;;;;;;;;;;;;;
Bromélia-imperial;Ornamentais;;;;;;;;;;;;;;;
Buriti;Agroflorestais;Carandá-Guaçu;Muriti;Palmeira-dos-Brejos;;;;;;;;;;;;
Buva;Outros;Voadeira;Coniza;;;;;;;;;;;;;
Caju;Agroflorestais;;;;;;;;;;;;;;;
Calêndula;Ornamentais;;;;;;;;;;;;;;;
Caliandra;Ornamentais;;;;;;;;;;;;;;;
Camarão-amarelo;Ornamentais;;;;;;;;;;;;;;;
Camélia-japonesa;Ornamentais;;;;;;;;;;;;;;;
Camomila;Medicinais/Chás;;;;;;;;;;;;;;;
Canafístula;Agroflorestais;Ibirá-puitá;;;;;;;Angico-vermelho;;;;;;;
Canafístula-de-besouro;Agroflorestais;Senna;;;;;;;;;;;;;;
Cana-do-brejo;Medicinais/Chás;Cana-de-macaco;Cana-de-velho;Cana-do-mato;;;;;;;;;;;;
Canela-batalha;Agroflorestais;;;;;;;;;;;;;;;
Canjerana;Agroflorestais;Cabralea;;;;;;;;;;;;;;
Cânhamo;Outros;Hemp;;;;;;;;;;;;;;
Capim-baquiária;Outros;Braquiária;;;;;;;;;Com qualquer planta;;;;;
Capim-dourado;Outros;;;;;;;;;;;;;;;
Capim-elefante;Outros;Napier;;;;;;;;;;;;;;
Capim-gordura;Outros;Catingueiro;;;;;;;;;;;;;;
Capim-mombaça;Outros;;;;;;;;;;;;;;;
Capim-santo;Medicinais/Chás;Capim-limão;;;;;;;;;;;;;;
Capim-vetiver;Outros;Vetiver;Falso-pachuli;;;;;;;;;;;;;
Capixingui;Agroflorestais;;;;;;;;;;;;;;;
Capororoca;Agroflorestais;;;;;;;;;;;;;;;
Cardamomo;Medicinais/Chás;;;;;;;;;;;;;;;
Cardo-mariano;Medicinais/Chás;;;;;;;;;;;;;;;
Carnaúba;Outros;Palmeira-dos-céus;;;;;;;;;;;;;;
Carqueja;Medicinais/Chás;;;;;;;;;;;;;;;
Carrapicho-de-carneiro;Outros;;;;;;;;;;;;;;;
Caruru;Outros;Bredo;;;;;;;;;;;;;;
Castanha-do-Brasil;Agroflorestais;Castanha-do-Pará;Castanha-do-Amazonas;Castanha-do-Acre;;;;;;;;;;;;
Casuarina;Agroflorestais;Pinheiro-da-austrália;;;;;;;;;;;;;;
Cavalinha;Medicinais/Chás;;;;;;;;;;;;;;;
Cebola;Alimentícia;;;;;;;;;;;;;;;
Cedro-rosa;Agroflorestais;Cedro-cetim;Cedro-fissilis;;;;Sol Pleno;Com qualquer planta;;;;;;POLETTO et al., 2020;;
Cenoura;Alimentícia;;;;;;;;;;;;;;;
Centella asiática;Medicinais/Chás;;;;;;;;;;;;;;;
Centeio;Outros;;;;;;;;;;;;;;;
Cerejeira;Ornamentais;Sakura;;;;;;;;;;;;;;
Chá-preto;Medicinais/Chás;;;;;;;;;;;;;;;
Chá-verde;Medicinais/Chás;;;;;;;;;;;;;;;
Ciclame;Ornamentais;;;;;;;;;;;;;;;
Cipó-cravo;Medicinais/Chás;;;;;;;;;;;;;;;
Cipó-titica;Outros;;;;;;;;;;;;;;;
Clematis;Ornamentais;;;;;;;;;;;;;;;
Clúsia;Ornamentais;;;;;;;;;;;;;;;
Colza;Outros;Canola;;;;;;;;;;;;;;
Copaíba;Agroflorestais;;;;;;;;;;;;;;;
Coração-de-negro;Agroflorestais;Ébano-oriental;;;;;;;;;;;;;;
Couve-flor;Alimentícia;;;;;;;;;;;;;;;
Cravo;Ornamentais;;;;;;;;;;;;;;;
Crotalária;Agroflorestais;;;;;;;;;;;;;;;
Cupuaçu;Agroflorestais;;;;;;;;;;;;;;;
Cúrcuma;Medicinais/Chás;;;;;;;;;;;;;;;
Cvatã;Agroflorestais;Cupania;;;;;;;;;;;;;;
Dália;Ornamentais;;;;;;;;;;;;;;;
Dente-de-leão;Medicinais/Chás;;;;;;;;;;;;;;;
Embaúba;Agroflorestais;Torém;Árvore-da-preguiça;;;;;;;;;;;;;
Erva-baleeira;Medicinais/Chás;;;;;;;;;;;;;
Erva-cidreira;Medicinais/Chás;;;;;;;;;;;;;;;
Erva-de-santa-luzia;Outros;;;;;;;;;;;;;;;
Erva-de-são-joão;Medicinais/Chás;;;;;;;;;;;;;;;
Erva-doce;Medicinais/Chás;;;;;;;;;;;;;;;
Erva-mate;Agroflorestais;;;;;;;;;;;;;;;
Ervilha;Alimentícia;;;;;;;;;;;;;;;
Espada-de-São-Jorge;Religiosidades;;;;;;;;;;;;;;;
Espinafre;Alimentícia;;;;;;;;;;;;;;;
Espinheira-santa;Agroflorestais;;;;;;;;;;;;;;;
Espinho-de-maricá;Agroflorestais;;;;;;Sol Pleno;;;;;;;;
Estrela-da-terra;Ornamentais;;;;;;;;;;;;;;;
Estrelítzia;Ornamentais;Ave-do-paraíso;;;;;;;;;;;;;;
Eucalipto;Agroflorestais;;;;;;;;;;;;;;;
Faveiro;Agroflorestais;Dimorphandra;;;;;;;;;;;;;;
Feijão-de-porco;Agroflorestais;;;;;;;;;;;;;;;
Figo;Alimentícia;;;;270;;;;;;;;POLLETTO et al., 2020;;;
Flor de lótus;Religiosidades;;;;;;;;;;;;;;;
Flor-de-maio;Ornamentais;;;;;;;;;;;;;;;
Fruta-do-Conde;Alimentícia;Araticum;Pinha;Ata;;;;;;;;;;;;
Gengibre;Medicinais/Chás;;;;;;;;;;;;;;;
Gérbera;Ornamentais;;;;;;;;;;;;;;;
Ginseng;Medicinais/Chás;;;;;;;;;;;;;;;
Girassol;Outros;;;;;;;;;;;;;;;
Girassol ornamental;Ornamentais;;;;;;;;;;;;;;;
Gliricídea;Agroflorestais;;;;;;;;;;;;;;;
Gloxínia;Ornamentais;;;;;;;;;;;;;;;
Grão-de-bico;Alimentícia;;;;;;;;;;;;;;;
Grevílea;Agroflorestais;Grevílea-gigante;;;;;;;;;;;;;;
Grumixama;Agroflorestais;Xaneira de Nega;Cumbixaba;Ibaporoiti;;;;;;;;;;;;
Guaco;Medicinais/Chás;;;;;;;;;;;;;;;
Guanandi;Agroflorestais;Jacareúba;;;;;;;;;;;;;;
Guandu;Agroflorestais;Feijão-guandu;;;;;;;;;;;;;;
Guapuruvu;Agroflorestais;Pata-de-faveira;Faveira;;;;;;;;;;;;;
Guaraná;Agroflorestais;Uaraná;;;;;;;;;;;;;;
Guarucaia;Agroflorestais;;;;;;Pleno Sol;;;;;;;POLETTO et al., 2020;;
Guaxuma;Outros;Malva-branca;;;;;;;;;;;;;;
Guanxuma-branca;Outros;;;;;;;;;;;;;;;
Guiné;Religiosidades;;;;;;;;;;;;;;;
Helicônia;Ornamentais;;;;;;;;;;;;;;;
Hibisco;Ornamentais;;;;;;;;;;;;;;;
Hissopo;Medicinais/Chás;;;;;;;;;;;;;;;
Hortelã;Medicinais/Chás;;;;;;;;;;;;;;;
Hortênsia;Ornamentais;;;;;;;;;;;;;;;
Iboga;Religiosidades;;;;;;;;;;;;;;;
Indaiá;Outros;Palmeira-indaiá;;;;;;;;;;;;;;
Ingá-cipó;Agroflorestais;Inga-do-mato;;;;;;;;;;;;;;
Ingá-feijão;Agroflorestais;;;;;;;;;;;;;;;
Inhame;Alimentícia;Cará;Cíamo;Fava-do-Egito;;;;;;;;;;;;
Ipê-amarelo;Agroflorestais;;;;;;;;;;;;;;;
Ipê-branco;Agroflorestais;;;;;;;;;;;;;;;
Ipê-rosa;Agroflorestais;;;;;;Meia Sombra;;;;;;;POLETTO et al., 2020;;
Ipê-roxo;Agroflorestais;Ipê-roxo-da-mata;;;;;Sombra;;;;;;;POLETTO et al., 2020;;
Ipê-verde;Agroflorestais;;;;;;;;;;;;;;;
Jabuticaba;Agroflorestais;Jaboticaba;;;;;;;;;;;;;;
Jacarandá-caroba;Agroflorestais;Caroba;;;;;;;;;;;;;;
Jacarandá-da-bahia;Agroflorestais;Caviúna;;;;;;;;;;;;;;
Jacarandá-mimoso;Agroflorestais;;;;;;;;;;;;;;;
Jambu;Alimentícia;Jamburana;Mastruço-do-Pará;Nhambu;;;;;;;;;;;;
Jatobá;Agroflorestais;;;;;;Meia Sombra;;;;;;;POLETTO et al., 2020;;
Jeguetibá-rosa;Agroflorestais;Estopeiro;Jequitibá-rosa;;;;Meia Sombra;;;;;;;POLETTO et al., 2020;;
Jenipapo;Agroflorestais;;;;;;;;;;;;;;;
Juá-de-capote;Outros;Nicandra;;;;;;;;;;;;;;
Juazeiro;Outros;Juá;Laranjinha-de-vaqueiro;;;;;;;;;;;;;
Jurema;Agroflorestais;;;;;;;;;;;;;;;
Jurubeba;Medicinais/Chás;;;;;;;;;;;;;;;
Juta;Outros;;;;;;;;;;;;;;;
Laranja;Alimentícia;;;;;;;;;;;;;;;
Lavanda;Ornamentais;;;;;;;;;;;;;;;
Lentilha;Alimentícia;;;;;;;;;;;;;;;
Leucena;Agroflorestais;;;;;;;;;;;;;;;
Licuri;Outros;Ouricuri;;;;;;;;;;;;;;
Limão;Alimentícia;;;;;;;;;;;;;;;
Linhaça;Outros;Linho;;;;;;;;;;;;;;
Lírio;Ornamentais;;;;;;;;;;;;;;;
Louro-pardo;Agroflorestais;Louro-batalha;;;;;;;;;;;;;;
Maçã;Alimentícia;;;;;;;;;;;;;;;
Macaúba;Outros;Bocaiúva;Chiclete-de-baiano;;;;;;;;;;;;;
Magnólia;Ornamentais;;;;;;;;;;;;;;;
Mamona;Outros;Rícino;Carrapateira;;;;;;;;;;;;;
Manacá-da-serra;Agroflorestais;;;;;;;;;;;;;;;
Mandioca;Alimentícia;Aipim;Macaxeira;;;;;;;;;;;;;
Manduirana;Agroflorestais;Alecrim-de-campinas;;;;;;;;;;;;;;
Manga;Alimentícia;;;;;;;;;;;;;;;
Manjericão;Alimentícia;Alfavaca;;;;;;;;;;;;;;
Maranta;Ornamentais;;;;;;;;;;;;;;;
Marapuama;Medicinais/Chás;;;;;;;;;;;;;;;
Maricá;Agroflorestais;Prasmará;;;;;;;;;;;;;;
Maxixe;Alimentícia;Galinha-Arrepiada;;;;;;;;;;;;;;
Melancia;Alimentícia;;;;;;;Babaçu;;;;;;SILVA, 2017;;
Melissa;Medicinais/Chás;Erva-cidreira;;;;;;;;;;;;;;
Melão;Alimentícia;;;;;;;;;;;;;;;
Milheto;Outros;;;;;;;;;;;;;;;
Milho;Alimentícia;;;;;;;;;;;;;;;
Monjoleiro;Agroflorestais;;;;;;;;;;;;;;;
Moringa;Agroflorestais;Acácia-branca;;;;;;;;;;;;;;
Mucuna-preta;Agroflorestais;;;;;;;;;;;;;;;
Mulungu;Agroflorestais;;;;;;;;;;;;;;;
Murici;Agroflorestais;Murici;Murixi;Fruta de Jacu;;;;;;;;;;;;
Mutamba;Agroflorestais;Pau-de-pomba;;;;;;;;;;;;;;
Narciso;Ornamentais;;;;;;;;;;;;;;;
Nim indiano;Agroflorestais;Neem;;;;;;;;;;;;;;
Onze-horas;Ornamentais;;;;;;;;;;;;;;;
Ora-pro-nóbis;Alimentícia;Orabrobó;Lobrobó;Lobrobô;;;;;;;;;;;;
Orquídea-cattleya;Ornamentais;;;;;;;;;;;;;;;
Paineira-rosa;Agroflorestais;Paineira;;;;;;;;;;;;;;
Palo Santo;Medicinais/Chás;;;;;;;;;;;;;;;
Palmeira-azul-do-cerrado;Agroflorestais;;;;;;;;;;;;;;;
Palmeira-jerivá;Agroflorestais;;;;;;;;;;;;;;;
Panã;Agroflorestais;Araticum;Cabeça de Nego;;;;;;;;;;;;
Passiflora;Medicinais/Chás;Flor-da-paixão;;;;;;;;;;;;;;
Pata-de-vaca;Agroflorestais;;;;;;;;;;;;;;;
Pau-brasil;Agroflorestais;;;;;;;;;;;;;;;
Pau-d'arco;Agroflorestais;;;;;;;;;;;;;;;
Pau-ferro;Agroflorestais;;;;;;;;;;;;;;;
Pau-formiga;Agroflorestais;;;;;;;;;;;;;;;
Pau-jacaré;Agroflorestais;Jacaré;;;;;;;;;;;;;;
Peiote;Religiosidades;Mescal;;;;;;;;;;;;;;
Pente-de-macaco;Agroflorestais;;;;;;;;;;;;;;;
Peônia;Ornamentais;;;;;;;;;;;;;;;
Pepino;Alimentícia;;;;;;;;;;;;;;;
Pequi;Agroflorestais;Piqui;Piquiá;Amêndoa-de-Espinho;;;;;;;;;;;;
Pera;Alimentícia;;;;;;;;;;;;;;;
Peregun;Religiosidades;Pau-d’água;;;;;;;;;;;;;;
Peroba-rosa;Agroflorestais;Peroba-comum;;;;;;;;;;;;;;
Petúnia;Ornamentais;;;;;;;;;;;;;;;
Piaçava;Outros;Piaçabeira;;;;;;;;;;;;;;
Picão-preto;Outros;Amor-de-vaca;;;;;;;;;;;;;;
Pimenta;Alimentícia;;;;;;;;;;;;;;;
Pinhão-manso;Outros;Pinhão;;;;;;;;;;;;;;
Piretro;Outros;;;;;;;;;;;;;;;
Pitanga;Agroflorestais;;;;;;;;;;;;;;;
Prímula;Ornamentais;;;;;;;;;;;;;;;
Pupunha;Alimentícia;;;;630;;;;;;;;;;;
Quaresmeira;Agroflorestais;Quaresmeira-roxa;;;;;;;;;;;;;;
Quina-do-cerrado;Outros;Quina-falsa;;;;;;;;;;;;;;
Rabo-de-cotia;Ornamentais;;;;;;;;;;;;;;;
Rapé;Religiosidades;Tabaco;;;;;;;;;;;;;;
Rosa;Ornamentais;;;;;;;;;;;;;;;
Saboneteira;Agroflorestais;Fruta-de-sabão;;;;;;;;;;;;;;
Sálvia;Religiosidades;;;;;;;;;;;;;;;
Samambaia;Ornamentais;;;;;;;;;;;;;;;
Sangra-d'água;Agroflorestais;Urucurana;;;;;;;;;;;;;;
Sansão-do-campo;Agroflorestais;Cabiúna;;;;;;;;;;;;;;
Sene;Medicinais/Chás;;;;;;;;;;;;;;;
Serralha;Outros;;;;;;;;;;;;;;;
Sibipiruna;Agroflorestais;;;;;;;;;;;;;;;
Sisal;Outros;Agave;;;;;;;;;;;;;;
Soja;Outros;;;;;;;;;;;;;;;
Sobrasil;Agroflorestais;Sobrasil-do-cerrado;;;;;Meia Sombra;;;;;;;POLETTO et al., 2020;;
Sombreiro;Agroflorestais;Carolina;;;;;;;;;;;;;;
Sorgo;Outros;;;;;;;;;;;;;;;
Sucupira;Agroflorestais;;;;;;;;;;;;;;;
Taboa;Outros;Enea;;;;;;;;;;;;;;
Tagetes;Outros;Cravo-de-defunto;;;;;;;;;;;;;;
Taiuiá;Agroflorestais;Tomate-de-são-caetano;;;;;;;;;;;;;;
Tamboril;Agroflorestais;Orelha-de-macaco;;;;;;;;;;;;;;
Taioba;Alimentícia;Macabo;Mangareto;Yautia;;;;;;;;;;;;
Tarumã;Agroflorestais;Tarumã-do-mato;;;;;;;;;;;;;;
Timbó;Outros;Cipó-timbó;;;;;;;;;;;;;;
Timburi;Agroflorestais;Timburi-do-cerrado;;;;;Pleno Sol;;;;;;;POLETTO et al., 2020;;
Tingui;Outros;Tingui-do-cerrado;;;;;;;;;;;;;;
Tiririca;Outros;Junça;;;;;;;;;;;;;;
Tomate;Alimentícia;;;;;;;;;;;;;;;
Toona ciliata;Agroflorestais;Cedro-australiano;;;;;;;;;;;;;;
Trevo-branco;Outros;;;;;;;;;;;;;;;
Trigo;Alimentícia;;;;;;;;;;;;;;;
Tucum;Outros;Tucumã-rasteiro;;;;;;;;;;;;;;
Tulipa;Ornamentais;;;;;;;;;;;;;;;
Umbu;Agroflorestais;;;;;;;;;;;;;;;
Umburana;Agroflorestais;Cumaru-nordestino;Ambaúrana;Angelim;;;;;;;;;;;;
Unha-de-gato;Medicinais/Chás;;;;;;;;;;;;;;;
Uva;Alimentícia;;;;;;;;;;;;;;;
Uvaia;Agroflorestais;Ubaia;Uvalha;;;;;;;;;;;;
Valeriana;Medicinais/Chás;;;;;;;;;;;;;;;
Vassourão-branco;Agroflorestais;;;;;;;;;;;;;;;
Vassourinha-de-botão;Outros;;;;;;;;;;;;;;;
Vassourinha-de-relógio;Religiosidades;Vassourinha;Vassoura-de-bruxa;;;;;;;;;;;;
Violeta-africana;Ornamentais;;;;;;;;;;;;;;;
Viuvinha;Ornamentais;;;;;;;;;;;;;;;
"""