# dados_iniciais.py

CSV_FABRICA = """Nome da Planta;Tipo;Nome Popular 1;Nome Popular 2;Nome Popular 3;Tempo de Colheita (Em Dias);Frequência de Rega (Em Dias);Quantidade de Sol;Planta que Cresce Bem Junto 1;Planta que Cresce Bem Junto 2;Planta que Cresce Bem Junto 3;Planta que Cresce Mal Junto 1;Planta que Cresce Mal Junto 2;Planta que Cresce Mal Junto 3;Fonte 1;Fonte 2;Fonte 3
Abóbora ornamental;Alimentícia;Abobrinha;Abóbora-de-tortéi;Abóbora-coração-de-boi;90;7;Sol Plano;Cerca-viva;;;;;;BARBIERI, 2012;FISCHER et al., 2012;
Monjoleiro;Agroflorestais;Espinheiro-preto;Angico-branco;Gorocaia;Sazonal: Mar-Out;7;Sol Pleno;Plantas de Sombra;;;;;;CARVALHO, 2008;;
Alcaçuz;Medicinais/Chás;;;;;;;;;;;;;;;
Alface;Alimentícia;Alface crespa;;;40;3;Sol Pleno;Abacateiro;;;;;;OLIVEIRA et al., 2018;BOITEUX et al., 2017;EMBRAPA, 1990
Alho;Alimentícia;;;;;;;;;;;;;;;
Amendoim-bravo;Agroflorestais;Amendoim;Ibiraró;Bálsamo;Sazonal: Mai-Ago;7;Sol Pleno;Frutíferas;Árvores de Crescimento Lento;;Povoamentos puros;;;CARVALHO, 2003;;
Andiroba;Agroflorestais;Jandiroba;Nandiroba;Penaíba;Sazonal: Set-Jan;5;Sol Pleno;Açaizeiro;Ucuúba;;;;;CARVALHO, 2014;;
Angélica;Medicinais/Chás;;;;;;;;;;;;;;;
Angico;Agroflorestais;Angico-paniculata;Unha-de-gato;;Sazonal: Mai-Jun;5;Sol Pleno;Frutíferas;Árvores de Crescimento Lento;;;;;CARVALHO, 2003;;
Angico-branco;Agroflorestais;Angico-liso;Curupaí;Cambuí;Sazonal: Jul-Nov;7;Sol Pleno;Culturas agrícolas;Povoamentos puros;;Plantas de Sombra;;;CARVALHO, 2003;;
Angico-cascudo;Agroflorestais;Angico-do-campo;Angico-do-cerrado;Angico-preto;Sazonal: Ago-Nov;7;Sol Pleno;Frutíferas;Árvores de Crescimento Lento;Leucena;;;;CARVALHO, 2003;;
Angico-gurucaia;Agroflorestais;Angelim-amarelo;Corocaia;Cambuí;Sazonal: Jun-Nov;7;Meia-Sombra;Culturas agrícolas;Plantas de Sombra;Acácia-negra;;;;CARVALHO, 2003;;
Angico-vermelho;Agroflorestais;Angico-da-mata;Aperta-ruão;;Sazonal: Abr-Out;15;Sol Pleno;Plantas de Sombra;Hortaliças e Folhosas;;;;;CARVALHO, 2003;;
Araribá-amarelo;Agroflorestais;Araraúva;Carijó;Mutumunju;Sazonal: Abr-Out;3;Sol Pleno;Culturas agrícolas;;;;;;CARVALHO, 2003;;
Araribá-rosa;Agroflorestais;Iriribá;Escovinha;Putumuju;Sazonal: Jul-Ago;7;Meia-Sombra;Culturas agrícolas;Plantas de Sombra;Cacaueiro;;;;CARVALHO, 2003;;
Araticum-cagão;Agroflorestais;Anona-cagona;Fruto-da-quaresma;Marolo;Sazonal: Dez-Mar;7;Sol Pleno;Culturas agrícolas;;;;;;CARVALHO, 2003;;
Araticum-da-mata;Agroflorestais;Araticum;Cortiça-Amarela;Pasmada-do-Mato;Sazonal: Jan-Mar;5;Sol Pleno;;;;;;;Carvalho, 2008;;
Araticum-de-porco;Agroflorestais;Ariticum-de-cavalo;Corticeira-de-comer;Araticum-alvadio;Sazonal: Nov;5;Sol Pleno;Culturas agrícolas;;;;;;;;
Aroeira-pimenteira;Agroflorestais;Abacaíba;Aguaraíba;Araguaraíba;Sazonal: Ago-Mar;7;Sol Pleno;Culturas agrícolas;Plantas de Sombra;Hortaliças e Folhosas;;;;CARVALHO, 2003;;
Aroeira-salsa;Agroflorestais;Aroeira-periquita;Anacauíta;Amescla;Sazonal: Dez-Fev;15;Sol Pleno;Culturas agrícolas;Plantas de Sombra;Hortaliças e Folhosas;;;;CARVALHO, 2003;;
Aroeira-verdadeira;Agroflorestais;Aderno;Almecega;Arendeúva;Sazonal: Ago-Nov;7;Sol Pleno;Candiúva;Angico-vermelho;Pinheiro-do-caribe;Povoamento puro;;;;;
Arruda;Religiosidades;;;;;;;;;;;;;;;
Babaçu;Medicinais/Chás;Baguaçu;Aguaçu;;;;;Melancia;;;;;;SILVA, 2017;;
Bacupari;Agroflorestais;Mucuri;Bacoparé;Bacuri;Sazonal: Nov-Fev;7;Sol Pleno;Povoamento puro;;;;;;CARVALHO, 2014;;
Braúna-do-sertão;Agroflorestais;Baraúna;Chamacoco;Pau-preto;Sazonal: Ago-Set;15;Sol Pleno;Hortaliças e Folhosas;;;;;;;
Bambu-japones;Religiosidades;;;;;;;;;;;;;;;
Banana;Alimentícia;;;;300;;;Brócolis;;;;;;POLETTO et al., 2020;;
Baobá;Religiosidades;;;;;;;;;;;;;;;
Baru;Agroflorestais;Coco-Pereba;Baru;Castanha-de-Burro;Sazonal: Set-Out;15;Sol Pleno;Cultura agrícola;Plantas de Sombra;;;;;CARVALHO, 2003;;
Batata;Alimentícia;;;;;;;;;;;;;;;
Begônia-rex;Ornamentais;;;;;;;;;;;;;;;
Bicuíba;Agroflorestais;Árvore-de-sebo;Bocuba;Bucuva;Sazonal: Out-Fev;7;Meia-Sombra;Cultura agrícola;;;;;;CARVALHO, 2003;;
Bonsai;Religiosidades;;;;;;;;;;;;;;;
Brócolis;Alimentícia;;;;;;;;;;;;;;;
Bromélia-imperial;Ornamentais;;;;;;;;;;;;;;;
Buriti-palito;Agroflorestais;Buriti-carandá;Carandá;Palmeira-de-leque;Sazonal:Out-Dez;7;Sol Pleno;;;;;;;CARVALHO,2010;;
Cambará;Agroflorestais;Balieira-preta;Candeia;Erva-d’ouro;Sazonal: Mar-Mai;7;Sol Pleno;;;;;;;CARVALHO, 2003;;
Calêndula;Ornamentais;;;;;;;;;;;;;;;
Caliandra;Ornamentais;;;;;;;;;;;;;;;
Camomila;Medicinais/Chás;;;;;;;;;;;;;;;
Cebola;Alimentícia;;;;;;;;;;;;;;;
Cedro-rosa;Agroflorestais;Cedro-cetim;Cedro-fissilis;;;;Sol Pleno;Com qualquer planta;;;;;;POLETTO et al., 2020;;
Cenoura;Alimentícia;;;;;;;;;;;;;;;
Chá-preto;Medicinais/Chás;;;;;;;;;;;;;;;
Chá-verde;Medicinais/Chás;;;;;;;;;;;;;;;
Ciclame;Ornamentais;;;;;;;;;;;;;;;
Copaíba;Agroflorestais;;;;;;;;;;;;;;;
Coração-de-negro;Agroflorestais;Ébano-oriental;;;;;;;;;;;;;;
Couve-flor;Alimentícia;;;;;;;;;;;;;;;
Cravo;Ornamentais;;;;;;;;;;;;;;;
Cúrcuma;Medicinais/Chás;;;;;;;;;;;;;;;
Cuvatã;Agroflorestais;Cupania;;;;;;;;;;;;;;
Dália;Ornamentais;;;;;;;;;;;;;;;
Embaúba;Agroflorestais;Torém;Árvore-da-preguiça;;;;;;;;;;;;;
Erva-cidreira;Medicinais/Chás;;;;;;;;;;;;;;;
Erva-doce;Medicinais/Chás;;;;;;;;;;;;;;;
Erva-mate;Agroflorestais;;;;;;;;;;;;;;;
Espada-de-São-Jorge;Religiosidades;;;;;;;;;;;;;;;
Espinafre;Alimentícia;;;;;;;;;;;;;;;
Espinheira-santa;Agroflorestais;;;;;;;;;;;;;;;
Faveira;Agroflorestais;;;;;;;;;;;;;;;
Flor de lótus;Religiosidades;;;;;;;;;;;;;;;
Gengibre;Medicinais/Chás;;;;;;;;;;;;;;;
Ginseng;Medicinais/Chás;;;;;;;;;;;;;;;
Girassol ornamental;Ornamentais;;;;;;;;;;;;;;;
Guanandi;Agroflorestais;Jacareúba;;;;;;;;;;;;;;
Guapuruvu;Agroflorestais;Pata-de-faveira;Faveira;;;;;;;;;;;;;
Guiné;Religiosidades;;;;;;;;;;;;;;;
Hissopo;Medicinais/Chás;;;;;;;;;;;;;;;
Hortelã;Medicinais/Chás;;;;;;;;;;;;;;;
Iboga;Religiosidades;;;;;;;;;;;;;;;
Ingá-cipó;Agroflorestais;Inga-do-mato;;;;;;;;;;;;;;
Ingá-feijão;Agroflorestais;;;;;;;;;;;;;;;
Ipê-rosa;Agroflorestais;;;;;;Meia Sombra;;;;;;;POLETTO et al., 2020;;
Ipê-roxo;Agroflorestais;Ipê-roxo-da-mata;;;;;Sombra;;;;;;;POLETTO et al., 2020;;
Jabuticaba;Agroflorestais;Jaboticaba;;;;;;;;;;;;;;
Jacarandá-da-Bahia;Agroflorestais;Caviúna;;;;;;;;;;;;;;
Jacarandá-do-cerrado;Agroflorestais;;;;;;;;;;;;;;;
Jacarandá-do-litoral;Agroflorestais;;;;;;;;;;;;;;;
Jatobá;Agroflorestais;;;;;;Meia Sombra;;;;;;;POLETTO et al., 2020;;
Jenipapeiro;Agroflorestais;;;;;;;;;;;;;;;
Jurema-preta;Agroflorestais;;;;;;;;;;;;;;;
Jurubeba;Medicinais/Chás;;;;;;;;;;;;;;;
Lírio;Ornamentais;;;;;;;;;;;;;;;
Louro-pardo;Agroflorestais;Louro-batalha;;;;;;;;;;;;;;
Magnólia;Ornamentais;;;;;;;;;;;;;;;
Manduirana;Agroflorestais;Alecrim-de-Campinas;;;;;;;;;;;;;;
Maricá;Agroflorestais;Prasmará;;;;;;;;;;;;;;
Melancia;Alimentícia;;;;;;;Babaçu;;;;;;SILVA, 2017;;
Melissa;Medicinais/Chás;Erva-cidreira;;;;;;;;;;;;;;
Melão;Alimentícia;;;;;;;;;;;;;;;
Mulungu;Agroflorestais;;;;;;;;;;;;;;;
Murici;Agroflorestais;Murici;Murixi;Fruta de Jacu;;;;;;;;;;;;
Mutamba;Agroflorestais;Pau-de-pomba;;;;;;;;;;;;;;
Paineira;Agroflorestais;Paineira;;;;;;;;;;;;;;
Pata-de-vaca;Agroflorestais;;;;;;;;;;;;;;;
Pau-brasil;Agroflorestais;;;;;;;;;;;;;;;
Pau-d'arco-amarelo;Agroflorestais;;;;;;;;;;;;;;;
Pau-ferro;Agroflorestais;;;;;;;;;;;;;;;
Pau-jacaré;Agroflorestais;Jacaré;;;;;;;;;;;;;;
Peiote;Religiosidades;Mescal;;;;;;;;;;;;;;
Peônia;Ornamentais;;;;;;;;;;;;;;;
Pequizeiro;Agroflorestais;Piqui;Piquiá;Amêndoa-de-Espinho;;;;;;;;;;;;
Peregun;Religiosidades;Pau-d’água;;;;;;;;;;;;;;
Peroba-rosa;Agroflorestais;Peroba-comum;;;;;;;;;;;;;;
Petúnia;Ornamentais;;;;;;;;;;;;;;;
Pimenta;Alimentícia;;;;;;;;;;;;;;;
Pimenta-de-macaco;Agroflorestais;;;;;;;;;;;;;;;
Pitangueira;Agroflorestais;;;;;;;;;;;;;;;
Quaresmeira;Agroflorestais;Quaresmeira-roxa;;;;;;;;;;;;;;
Rosa;Ornamentais;;;;;;;;;;;;;;;
Saboneteira;Agroflorestais;Fruta-de-sabão;;;;;;;;;;;;;;
Samambaia;Ornamentais;;;;;;;;;;;;;;;
Sangra-d'água;Agroflorestais;Urucurana;;;;;;;;;;;;;;
Sibipiruna;Agroflorestais;;;;;;;;;;;;;;;
Sobrasil;Agroflorestais;Sobrasil-do-cerrado;;;;;Meia Sombra;;;;;;;POLETTO et al., 2020;;
Sucupira;Agroflorestais;;;;;;;;;;;;;;;
Tarumã;Agroflorestais;Tarumã-do-mato;;;;;;;;;;;;;;
Tomate;Alimentícia;;;;;;;;;;;;;;;
Tulipa;Ornamentais;;;;;;;;;;;;;;;
Umbuzeiro;Agroflorestais;;;;;;;;;;;;;;;
Ucuúba-do-cerrado;Agroflorestais;Ucuúba-do-cerrado;;;;;;;;;;;;;;
Uva;Alimentícia;;;;;;;;;;;;;;;
Uvaieira;Agroflorestais;Ubaia;Uvalha;;;;;;;;;;;;;
Vassourão-branco;Agroflorestais;;;;;;;;;;;;;;;
"""